plugins:
  - jekyll-sitemap

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - .github
  - vite.config.ts
  - tsconfig.json
  - tsconfig.app.json
  - tsconfig.node.json
  - postcss.config.js
  - tailwind.config.ts
  - eslint.config.js
  - vitest.config.ts

# GitHub Pages settings
markdown: kramdown

